FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json ./

COPY apps/nextjs-app ./apps/nextjs-app
COPY packages ./packages

RUN npm install
RUN npm run db:generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]