FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json ./

COPY apps/docs ./apps/docs
COPY packages ./packages

RUN npm install

RUN npm run build

EXPOSE 3010

CMD ["npm", "run", "start"]